{
  imports = [
    ./agent-indicator.nix
    ./agents.nix
    ./ai-resources.nix
    ./annot.nix
    ./anthropic-skills.nix
    ./betterfox.nix
    ./basic-memory.nix
    ./chunkhound.nix
    ./claude-code.nix
    ./context-mode.nix
    ./crush.nix
    ./impeccable.nix
    ./lean-ctx.nix
    ./lsp.nix
    ./plannotator.nix
    ./playwriter.nix
    ./superpowers.nix
    ./taste-skill.nix
  ];
}
