local sidebars = {
    "DiffViewFiles",
    "NeogitStatus",
    "fugitive",
    "snacks_layout_box",
    "undotree",
}

local M = {
    treesitter = {
        "bash",
        "css",
        "diff",
        "dockerfile",
        "fish",
        "git_config",
        "git_rebase",
        "gitattributes",
        "gitcommit",
        "gitignore",
        "go",
        "graphql",
        "hcl",
        "html",
        "hurl",
        "java",
        "javascript",
        "json",
        "jsonc",
        "lua",
        "markdown",
        "nix",
        "python",
        "rust",
        "scss",
        "sql",
        "svelte",
        "terraform",
        "tmux",
        "todotxt",
        "toml",
        "tsx",
        "typescript",
        "vim",
        "yaml",
    },
    excludes = {
        "TelescopePrompt",
        "TelescopeResults",
        "bigfile",
        "blink-cmp-documentation",
        "blink-cmp-menu",
        "blink-cmp-signature",
        "cmp_docs",
        "cmp_menu",
        "fugitiveblame",
        "gitcommit",
        "help",
        "lspinfo",
        "notify",
        "oil",
        "oil_preview",
        "prompt",
        "qf",
        "snacks_picker_input",
        "snacks_picker_list",
        "snacks_picker_preview",
        unpack(sidebars),
    },
    sidebars = sidebars,
}

return M
