return {
    "samir-roy/code-bridge.nvim",
    cmd = {
        "CodeBridgeTmux",
        "CodeBridgeTmuxAll",
        "CodeBridgeTmuxInteractive",
        "CodeBridgeTmuxAllInteractive",
        "CodeBridgeTmuxDiff",
        "CodeBridgeTmuxDiffStaged",
        "CodeBridgeTmuxRecent",
        "CodeBridgeTmuxRecentInteractive",
        "CodeBridgeTmuxDiagnostics",
        "CodeBridgeTmuxDiagnosticsAll",
        "CodeBridgeTmuxDiagnosticsErrors",
        "CodeBridgeTmuxDiagnosticsErrorsAll",
        "CodeBridgeQuery",
        "CodeBridgeChat",
        "CodeBridgeHide",
        "CodeBridgeShow",
        "CodeBridgeWipe",
        "CodeBridgeCancelQuery",
        "CodeBridgeResumePrompt",
    },
    keys = {
        -- send context via tmux
        { "<leader>ct", "<CMD>CodeBridgeTmux<CR>", mode = { "n", "v" }, desc = "Send file" },
        { "<leader>ca", "<CMD>CodeBridgeTmuxAll<CR>", mode = { "n", "v" }, desc = "Send all buffers" },
        { "<leader>ci", "<CMD>CodeBridgeTmuxInteractive<CR>", mode = { "n", "v" }, desc = "Interactive prompt" },
        { "<leader>cA", "<CMD>CodeBridgeTmuxAllInteractive<CR>", desc = "Interactive all buffers" },
        { "<leader>cd", "<CMD>CodeBridgeTmuxDiff<CR>", desc = "Send diff" },
        { "<leader>cD", "<CMD>CodeBridgeTmuxDiffStaged<CR>", desc = "Send staged diff" },
        { "<leader>cr", "<CMD>CodeBridgeTmuxRecent<CR>", desc = "Send recent" },
        { "<leader>cR", "<CMD>CodeBridgeTmuxRecentInteractive<CR>", desc = "Interactive recent" },
        { "<leader>ce", "<CMD>CodeBridgeTmuxDiagnostics<CR>", desc = "Send diagnostics" },
        { "<leader>cE", "<CMD>CodeBridgeTmuxDiagnosticsAll<CR>", desc = "Send all diagnostics" },
        { "<leader>cx", "<CMD>CodeBridgeTmuxDiagnosticsErrors<CR>", desc = "Send errors" },
        { "<leader>cX", "<CMD>CodeBridgeTmuxDiagnosticsErrorsAll<CR>", desc = "Send all errors" },
        -- chat interface
        { "<leader>cq", "<CMD>CodeBridgeQuery<CR>", mode = { "n", "v" }, desc = "Query with context" },
        { "<leader>cc", "<CMD>CodeBridgeChat<CR>", desc = "Chat" },
        { "<leader>ch", "<CMD>CodeBridgeHide<CR>", desc = "Hide chat" },
        { "<leader>cs", "<CMD>CodeBridgeShow<CR>", desc = "Show chat" },
        { "<leader>cw", "<CMD>CodeBridgeWipe<CR>", desc = "Wipe chat" },
        { "<leader>ck", "<CMD>CodeBridgeCancelQuery<CR>", desc = "Cancel query" },
        { "<leader>cp", "<CMD>CodeBridgeResumePrompt<CR>", desc = "Resume prompt" },
    },
    opts = {
        tmux = {
            target_mode = "find_process",
            switch_to_target = true,
            process_name = {
                "claude",
                "opencode",
            },
        },
    },
}
