{
  lib,
  stdenv,
  lean-ctx,
  bash,
}:

stdenv.mkDerivation {
  pname = "lean-ctx-assets";
  # Tracks the pinned lean-ctx binary so the generated assets stay in sync.
  version = lean-ctx.version;

  # Assets are generated from the lean-ctx binary; there is no upstream source.
  dontUnpack = true;
  dontConfigure = true;
  dontBuild = true;

  buildInputs = [
    lean-ctx
    bash
  ];

  # `init` runs a full global init (it even ignores --help and mutates $HOME),
  # so the binary must never run against the real $HOME — only in this sandbox.
  LEAN_CTX_NO_UPDATE_CHECK = "1";

  installPhase = ''
    runHook preInstall

    LC="${lean-ctx}/bin/lean-ctx"

    # Isolated fake HOME so init writes nowhere near the build host's real $HOME.
    FAKE="$(mktemp -d)"
    export HOME="$FAKE"
    export XDG_CONFIG_HOME="$FAKE/.config"
    export XDG_DATA_HOME="$FAKE/.local/share"
    export XDG_CACHE_HOME="$FAKE/.cache"
    export XDG_STATE_HOME="$FAKE/.local/state"

    # 1. Bash hook -> $out/env.sh (the eval-pattern hook sourced via
    #    CLAUDE_ENV_FILE / BASH_ENV). init emits WARNs about not being able to
    #    write optional _lc shims into the read-only store; those are harmless.
    "$LC" init >/dev/null 2>&1 </dev/null || true
    install -Dm644 "$FAKE/.config/lean-ctx/env.sh" "$out/env.sh"

    # 2. claude assets: CLAUDE.md + skills/lean-ctx/**
    "$LC" init --agent claude --mode hybrid >/dev/null 2>&1 </dev/null || true
    install -Dm644 "$FAKE/.claude/CLAUDE.md" "$out/claude/CLAUDE.md"
    mkdir -p "$out/claude/skills"
    cp -r "$FAKE/.claude/skills/lean-ctx" "$out/claude/skills/lean-ctx"

    # 3. opencode assets: AGENTS.md
    "$LC" init --agent opencode --mode hybrid >/dev/null 2>&1 </dev/null || true
    install -Dm644 "$FAKE/.config/opencode/AGENTS.md" "$out/opencode/AGENTS.md"

    # 4. opencode shell wrapper — activates the hook only inside opencode's
    #    bash sessions (LEAN_CTX_AGENT drives _lc_is_agent(); BASH_ENV loads the
    #    hook). The store path is fixed at build time, so no global env needed.
    cat > "$out/opencode-shell" <<EOF
#!/usr/bin/env bash
# Generated by lean-ctx-assets — opencode's scoped shell wrapper.
# Do not edit; regenerate via the lean-ctx-assets derivation.
export LEAN_CTX_AGENT=1
export BASH_ENV="$out/env.sh"
exec bash "\$@"
EOF
    chmod 0755 "$out/opencode-shell"

    runHook postInstall
  '';

  meta = with lib; {
    description = "Generated lean-ctx bash hook, agent rules/skill, and opencode shell wrapper";
    license = licenses.mit;
    platforms = platforms.all;
    maintainers = [ ];
  };
}
