local sidebars = {
    "dbui",
    "DiffViewFiles",
    "NvimTree",
    "Outline",
    "undotree",
}

return {
    treesitter = {
        "css",
        "dockerfile",
        "fish",
        "git_config",
        "git_rebase",
        "gitattributes",
        "gitcommit",
        "gitignore",
        "go",
        "graphql",
        "html",
        "java",
        "javascript",
        "json",
        "jsonc",
        "lua",
        "markdown",
        "nix",
        "python",
        "rust",
        "scss",
        "svelte",
        "toml",
        "typescript",
        "vim",
        "yaml",
    },
    extras = {
        "html5",
        "javascriptreact",
        "jsx",
        "sh",
        "typescriptreact",
    },
    excludes = {
        "dirbuf",
        "cmp_docs",
        "cmp_menu",
        "fugitive",
        "fugitiveblame",
        "gitcommit",
        "help",
        "lspinfo",
        "NeogitStatus",
        "notify",
        "packer",
        "prompt",
        "qf",
        "TelescopePrompt",
        "TelescopeResults",
        unpack(sidebars),
    },
    sidebars = sidebars,
}
